import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import JSZip from 'jszip';
const legacy=JSON.parse(readFileSync(new URL('../fixtures/legacy-v1.json',import.meta.url)));
test('crop pan, cancel, undo, reload and shared PNG/CBZ preserve original and lettering',async({page})=>{
 await page.goto('/');
 await page.evaluate(async fixture=>{const {saveProject}=await import('/src/bridge.js');await saveProject(fixture);},legacy);
 await page.reload();await page.getByRole('button',{name:'コマ割り編集',exact:true}).click();
 await page.getByRole('button',{name:'画像トリミング',exact:true}).click();
 const slot=page.getByTestId('layout-slot-0');
 await slot.click({position:{x:60,y:45}});await page.getByRole('button',{name:'このコマを全面表示にする'}).click();
 const load=()=>page.evaluate(async()=>await (await import('/src/bridge.js')).loadProject());
 const p=await load(),id=p.panels[0].id;expect(p.layout.imageCrops[id]).toEqual({zoom:1,x:.5,y:.5});
 await slot.click({position:{x:60,y:45}});await page.getByLabel('画像の拡大率',{exact:true}).selectOption('2');
 await expect.poll(async()=>(await load()).layout.imageCrops[id].zoom).toBe(2);
 const points=await slot.getAttribute('points');await slot.scrollIntoViewIfNeeded();const b=await slot.boundingBox();
 await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+35,b.y+b.height/2+25);await page.mouse.up();
 await expect.poll(async()=> (await load()).layout.imageCrops[id].x).toBeLessThan(.5);
 const after=(await load()).layout.imageCrops[id];expect(await slot.getAttribute('points')).toBe(points);
 await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+60,b.y+b.height/2);await page.keyboard.press('Escape');await page.mouse.up();
 expect((await load()).layout.imageCrops[id]).toEqual(after);
 await page.getByRole('button',{name:'枠をUndo'}).click();await expect.poll(async()=>(await load()).layout.imageCrops[id].x).toBe(.5);
 await page.getByRole('button',{name:'枠をRedo'}).click();await expect.poll(async()=>(await load()).layout.imageCrops[id]).toEqual(after);
 await page.reload();expect((await load()).layout.imageCrops[id]).toEqual(after);expect((await load()).panels).toEqual(p.panels);
 const result=await page.evaluate(async()=>{const p=await (await import('/src/bridge.js')).loadProject();const {pageLayers,pagePNG,exportCBZ}=await import('/src/render.js');const {pagePanels}=await import('/src/layout.js');const pg=p.layout.pages[0],panels=pagePanels(p,pg);
 const before=await pageLayers(panels,p.snapshots,[], 'ja','overlay',pg),after=await pageLayers(panels,p.snapshots,[],'ja','overlay',pg,false,p.layout.imageCrops);
 const png=await pagePNG(panels,p.snapshots,[],'ja',pg,false,p.layout.imageCrops);
 return {sameText:before===after,png:png.split(',')[1],cbz:Array.from(new Uint8Array(await (await exportCBZ(p)).arrayBuffer()))};});
 expect(result.sameText).toBe(true);const zip=await JSZip.loadAsync(result.cbz);expect(await zip.file('001.png').async('base64')).toBe(result.png);
 await page.getByRole('button',{name:'コマ割り編集',exact:true}).click();await page.screenshot({path:'test-results/image-crop.png',fullPage:true});
});
