import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const fixture = JSON.parse(readFileSync(new URL('../fixtures/legacy-v1.json', import.meta.url)));
test('LEGACY-01 reload, Undo images, and byte-identical PNG/CBZ page content', async ({ page }) => {
  await page.goto('/');
  const result = await page.evaluate(async legacy => {
    const { migrateProject } = await import('/src/revisions.js');
    const { pagePNG, exportCBZ } = await import('/src/render.js');
    const { saveProject } = await import('/src/bridge.js');
    const project = await migrateProject(legacy);
    const before = await pagePNG(legacy.panels, legacy.snapshots);
    const after = await pagePNG(project.panels, project.snapshots);
    const undo = await pagePNG(project.history[0].panels, project.snapshots);
    const cbz = await exportCBZ(project);
    const originalZip = await exportCBZ(legacy);
    await saveProject(project);
    return { samePNG: before === after, sameUndo: undo === before, cbzSize: cbz.size, legacyCbzSize: originalZip.size };
  }, fixture);
  expect(result.samePNG).toBe(true);
  expect(result.sameUndo).toBe(true);
  expect(result.cbzSize).toBeGreaterThan(100);
  expect(result.cbzSize).toBe(result.legacyCbzSize);
  await page.reload();
  await expect(page.locator('.caption')).toContainText('「原文です」');
  await expect(page.locator('.art img')).toHaveAttribute('src', fixture.panels[0].image);
  await page.getByRole('button', { name: '元に戻す' }).click();
  await page.reload();
  await expect(page.locator('.art img')).toHaveAttribute('src', fixture.history[0].panels[0].image);
  await page.screenshot({ path: 'test-results/legacy-migrated.png', fullPage: true });
});
